Music_Web/Models/OrderViewModel.cs
using Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Music_Web.Models
{
    public class OrderViewModel
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        [Display(Name = "Customer Name")]
        public string CFirstName { get; set; }
        public string CLastName { get; set; }
        public string CPhone { get; set; }
        [Display(Name = "Employee ID")]
        public int EmployeeID { get; set; }
        [Display(Name = "Employee Name")]
        public string EFirstName { get; set; }
        [Display(Name = "Last Name")]
        public string ELastName { get; set; }
        [Display(Name = "Total Order's Value")]
        public decimal? TotalOrder { get; set; }
        [Display(Name = "Date of Order")]
        public DateTime? DateOfOrder { get; set; }
        public IEnumerable<OrderDetailViewModel> OrderDetails { get; set; }
    }
}

Music_Web/Controllers/OrderController.cs
using DataAccess;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Models;
using Music_Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music_Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly MusicStore_Context _context;
        public OrderController(MusicStore_Context context)
        {
            _context = context;
        }
        // GET: OrderController
        public ActionResult Index()
        {
            var list = _context.OrderInfos.Include(m => m.Customer).Include(m => m.Employee).ToList();
            List<OrderViewModel> model = new();
            foreach (var item in list)
            {
                var sum = _context.OrderDetails.Where(m => m.OrderInfoID == item.ID).Sum(m => m.QuantitySold * m.UnitPrice);
                var order = new OrderViewModel()
                {
                    ID = item.ID,
                    DateOfOrder = item.DateOfOrder,
                    TotalOrder = Math.Round((decimal)sum,2),
                    EmployeeID = item.Employee.ID,
                    EFirstName = item.Employee.FirstName,
                    ELastName = item.Employee.LastName,
                    CustomerID = item.Customer.ID,
                    CFirstName = item.Customer.FirstName,
                    CLastName = item.Customer.LastName,
                    CPhone = item.Customer.Phone
                };
                model.Add(order);
            }
            return View(model);
        }

        // GET: OrderController/Details/5
        public async Task<IActionResult> Details(int id)
        {

            return await ViewGenerator(id);
        }
        public async Task<IActionResult> ViewGenerator(int id)
        {
            var order = await _context.OrderInfos.FindAsync(id);
            var employee = await _context.Employees.FindAsync(order.EmployeeID);
            var customer = await _context.Customers.FindAsync(order.CustomerID);
            List<OrderDetailViewModel> details = new();
            foreach (OrderDetail item in _context.OrderDetails.Where(m => m.OrderInfoID == id))
            {
                var instrumentInfo = _context.Instruments.Find(item.InstrumentID);
                OrderDetailViewModel detailItem = new()
                {
                    ID = item.ID,
                    InstrumentID = item.InstrumentID,
                    Brand = instrumentInfo.Brand,
                    Model = instrumentInfo.Model,
                    Type = instrumentInfo.InstrumentType,
                    UnitPrice = item.UnitPrice,
                    QuantitySold = item.QuantitySold,
                    TotalPrice = Math.Round((decimal)(item.UnitPrice * item.QuantitySold),2)
                };
                details.Add(detailItem);
            }
            var sum = details.Sum(m => m.TotalPrice);
            var model = new OrderViewModel
            {
                ID = id,
                DateOfOrder = order.DateOfOrder,
                TotalOrder = Math.Round((decimal)sum,2),
                EmployeeID = employee.ID,
                EFirstName = employee.FirstName,
                ELastName = employee.LastName,
                CustomerID = customer.ID,
                CFirstName = customer.FirstName,
                CLastName = customer.LastName,
                CPhone = customer.Phone,
                OrderDetails = details
            };
            return View(model);
        }
        // GET: OrderController/Create
        public ActionResult Create()
        {
            ViewData["EmployeeID"] = new SelectList(_context.Employees, "ID", "ID");
            ViewData["CustomerID"] = new SelectList(_context.Customers, "ID", "ID");
            return View(new OrderInfo());
        }

        // POST: OrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OrderInfo orderInfo)
        {
            try
            {
                _context.Add(orderInfo);
                await _context.SaveChangesAsync();

                // Get the Id of newest item
                var newItem = await _context.OrderInfos.OrderBy(m => m.ID).LastAsync();
                return RedirectToAction(nameof(Edit), new { id = newItem.ID });
            }
            catch
            {
                ViewData["EmployeeID"] = new SelectList(_context.Employees, "ID", "ID", orderInfo.EmployeeID.ToString());
                ViewData["CustomerID"] = new SelectList(_context.Customers, "ID", "ID", orderInfo.CustomerID.ToString());

                return View(orderInfo);
            }
        }

        // GET: OrderController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var orderInfo = await _context.OrderInfos.FindAsync(id);
            ViewData["EmployeeID"] = new SelectList(_context.Employees, "ID", "ID", orderInfo.EmployeeID.ToString());
            ViewData["CustomerID"] = new SelectList(_context.Customers, "ID", "ID", orderInfo.CustomerID.ToString());
            return await ViewGenerator(id);
        }

        // POST: OrderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, OrderViewModel orderInfo)
        {
            try
            {
                var item = await _context.OrderInfos.FindAsync(id);
                item.CustomerID = orderInfo.CustomerID;
                item.EmployeeID = orderInfo.EmployeeID;
                item.DateOfOrder = orderInfo.DateOfOrder;
                _context.OrderInfos.Update(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewData["EmployeeID"] = new SelectList(_context.Employees, "ID", "ID", orderInfo.EmployeeID.ToString());
                ViewData["CustomerID"] = new SelectList(_context.Customers, "ID", "ID", orderInfo.CustomerID.ToString());
                return View(orderInfo);
            }
        }

        // GET: OrderController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var orderInfo = await _context.OrderInfos.FindAsync(id);
                _context.Remove(orderInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Details), new { id });
            }
        }
    }
}

Music_Web/Controllers/OrderDetailController.cs
using DataAccess;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music_Web.Controllers
{
    public class OrderDetailController : Controller
    {
        private readonly MusicStore_Context _context;
        public OrderDetailController(MusicStore_Context context)
        {
            _context = context;
        }
        // GET: OrderDetailController/Create
        public ActionResult Create(int id)
        {
            ViewData["InstrumentID"] = new SelectList(_context.Instruments, "ID", "ID");
            return View(new OrderDetail() { OrderInfoID = id});
        }

        // POST: OrderDetailController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OrderDetail orderDetail)
        {
            try
            {
                var item = new OrderDetail
                {
                    ID = null,
                    OrderInfoID = orderDetail.OrderInfoID,
                    InstrumentID = orderDetail.InstrumentID,
                    QuantitySold = orderDetail.QuantitySold,
                    UnitPrice = orderDetail.UnitPrice
                };

                _context.Add(item);
                var instrument = await _context.Instruments.FindAsync(orderDetail.InstrumentID);
                instrument.Quantity -= orderDetail.QuantitySold;
                if (instrument.Quantity < 0)
                {
                    ModelState.AddModelError(string.Empty,"Not enough instrument in stock");
                    ViewData["InstrumentID"] = new SelectList(_context.Instruments, "ID", "ID", orderDetail.InstrumentID.ToString());
                    return View(orderDetail);
                }
                _context.Update(instrument);
                await _context.SaveChangesAsync();
                return RedirectToAction("Edit", "Order", new { id = orderDetail.OrderInfoID });
            }
            catch
            {
                ViewData["InstrumentID"] = new SelectList(_context.Instruments, "ID", "ID", orderDetail.InstrumentID.ToString());
                return View(orderDetail);
            }
        }
        public async Task<IActionResult> Details(int id)
        {
            var item = await _context.OrderDetails.FindAsync(id);
            if (item == null) return NotFound();
            return View(item);
        }
        // GET: OrderDetailController/Edit/5
        public ActionResult Edit(int id)
        {
            var item = _context.OrderDetails.Find(id);
            ViewData["InstrumentID"] = new SelectList(_context.Instruments, "ID", "ID",item.InstrumentID.ToString());
            return View(item);
        }

        // POST: OrderDetailController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, OrderDetail orderDetail)
        {
            try
            {
                var item = await _context.OrderDetails.FindAsync(id);
                var instrument = await _context.Instruments.FindAsync(orderDetail.InstrumentID);
                instrument.Quantity = instrument.Quantity + item.QuantitySold - orderDetail.QuantitySold;
                if (instrument.Quantity < 0)
                {
                    ModelState.AddModelError(string.Empty, "Not enough instrument in stock");
                    ViewData["InstrumentID"] = new SelectList(_context.Instruments, "ID", "ID", orderDetail.InstrumentID.ToString());
                    return View(orderDetail);
                }
                _context.Update(instrument);
                
                item.InstrumentID = orderDetail.InstrumentID;
                item.QuantitySold = orderDetail.QuantitySold;
                item.UnitPrice = orderDetail.UnitPrice;
                _context.Update(item);

                
                await _context.SaveChangesAsync();
                return RedirectToAction("Edit", "Order", new { id = orderDetail.OrderInfoID});
            }
            catch
            {
                ViewData["InstrumentID"] = new SelectList(_context.Instruments, "ID", "ID",orderDetail.InstrumentID.ToString());
                return View(orderDetail);
            }
        }

        // GET: OrderDetailController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }
    }
}

Music_Web/Views/Order/Create.cshtml
@model Models.OrderInfo

@{
    ViewData["Title"] = "Add Order";
    ViewBag.OActive = "active";
}
<hr />
<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Employee" class="control-label"></label>
        <select asp-for="EmployeeID" class="form-control" asp-items="ViewBag.EmployeeID"></select>
    </div>
    <div class="form-group">
        <label asp-for="Customer" class="control-label"></label>
        <select asp-for="CustomerID" class="form-control" asp-items="ViewBag.CustomerID"></select>
    </div>
    <div class="form-group">
        <label asp-for="DateOfOrder" class="control-label"></label>
        <input asp-for="DateOfOrder" class="form-control" required/>
        <span asp-validation-for="DateOfOrder" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Add" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Music_Web/Views/Order/Details.cshtml
@model Music_Web.Models.OrderViewModel
@{
    ViewData["Title"] = "Order Details";
    ViewBag.OActive = "active";
}
<div>
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" href="#first" aria-controls="first" role="tab" data-toggle="tab">Basic Info</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#second" aria-controls="second" role="tab" data-toggle="tab">Detailed Info</a>
        </li>
    </ul>
</div>

<div class="tab-content mt-3">

    <div role="tabpanel" class="tab-pane active" id="first">
        <dl class="row">
            <dt class="col-sm-2 font-weight-bold">
                @Html.DisplayNameFor(model => model.DateOfOrder)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DateOfOrder)
            </dd>
            <dt class="col-sm-2 font-weight-bold">
                Customer ID
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CustomerID)
            </dd>
            <dt class="col-sm-2 font-weight-bold">
                Customer Name
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CFirstName)
                @Html.Display(" ")
                @Html.DisplayFor(model => model.CLastName)
            </dd>
            <dt class="col-sm-2 font-weight-bold">
                Customer Phone Number
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CPhone)
            </dd>
            <dt class="col-sm-2 font-weight-bold">
                Employee ID
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.EmployeeID)
            </dd>
            <dt class="col-sm-2 font-weight-bold">
                Employee Name
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.EFirstName)
                @Html.Display(" ")
                @Html.DisplayFor(model => model.ELastName)
            </dd>
            <dt class="col-sm-2 font-weight-bold">
                Total Order's Value
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.TotalOrder)
            </dd>
        </dl>
        <div class="mb-2">
            <a asp-action="Edit" asp-route-id="@Model.ID" class="btn btn-primary mr-2">Edit</a>
            <a data-toggle="modal" data-target="#deleteModal" class="btn btn-danger">Delete</a>
        </div>
        <a asp-action="Index">Back to List</a>
    </div>
    <div role="tabpanel" class="tab-pane" id="second">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Instrument ID
                    </th>
                    <th>
                        Instrument Type
                    </th>
                    <th>
                        Instrument Model
                    </th>
                    <th>
                        Instrument Brand
                    </th>
                    <th>
                        Unit Price
                    </th>
                    <th>
                        Quantity Sold
                    </th>
                    <th>
                        Total Price
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.OrderDetails)
                {
                    <tr>
                        <td>
                            @item.InstrumentID
                        </td>
                        <td>
                            @item.Type
                        </td>
                        <td>
                            @item.Model
                        </td>
                        <td>
                            @item.Brand
                        </td>
                        <td>
                            $@item.UnitPrice
                        </td>
                        <td>
                            @item.QuantitySold
                        </td>
                        <td>
                            $@item.TotalPrice
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div class="modal fade show" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteLabel" aria-hidden="true" style="display: none">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteLabel">Are you sure?</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to
                <label class="text-danger">permanently delete </label>
                this order? This process cannot be undone.
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <a asp-action="Delete" asp-route-id="@Model.ID" class="btn btn-danger">Yes, delete it</a>
            </div>
        </div>
    </div>
</div>

Music_Web/Views/Order/Edit.cshtml
@model Music_Web.Models.OrderViewModel
@{
    ViewData["Title"] = "Edit Order";
    ViewBag.OActive = "active";
}
<div>
    <ul class="nav nav-tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" href="#first" aria-controls="first" role="tab" data-toggle="tab">Basic Info</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#second" aria-controls="second" role="tab" data-toggle="tab">Detailed Info</a>
        </li>
    </ul>
</div>
<div class="tab-content mt-3">
    <div role="tabpanel" class="tab-pane active" id="first">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <dl class="row">
                <dt class="col-sm-2 font-weight-bold">
                    @Html.DisplayNameFor(model => model.DateOfOrder)
                </dt>
                <dd class="col-sm-10">
                    <input asp-for="DateOfOrder" class="form-control" />
                </dd>
                <dt class="col-sm-2 font-weight-bold">
                    Customer ID
                </dt>
                <dd class="col-sm-10">
                    <select asp-for="CustomerID" class="form-control" asp-items="ViewBag.CustomerID"></select>
                </dd>
                <dt class="col-sm-2 font-weight-bold">
                    Customer Name
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.CFirstName)
                    @Html.Display(" ")
                    @Html.DisplayFor(model => model.CLastName)
                </dd>
                <dt class="col-sm-2 font-weight-bold">
                    Customer Phone Number
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.CPhone)
                </dd>
                <dt class="col-sm-2 font-weight-bold">
                    Employee ID
                </dt>
                <dd class="col-sm-10">
                    <select asp-for="EmployeeID" class="form-control" asp-items="ViewBag.EmployeeID"></select>
                </dd>
                <dt class="col-sm-2 font-weight-bold">
                    Employee Name
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.EFirstName)
                    @Html.Display(" ")
                    @Html.DisplayFor(model => model.ELastName)
                </dd>
                <dt class="col-sm-2 font-weight-bold">
                    Total Order's Value
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.TotalOrder)
                </dd>
            </dl>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
            <div>
                <a asp-action="Index">Back to List</a>
            </div>
        </form>
    </div>
    <div role="tabpanel" class="tab-pane" id="second">
        <p>
            <a asp-action="Create" asp-controller="OrderDetail" asp-route-id="@Model.ID">Add</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th>
                        Instrument ID
                    </th>
                    <th>
                        Instrument Type
                    </th>
                    <th>
                        Instrument Model
                    </th>
                    <th>
                        Instrument Brand
                    </th>
                    <th>
                        Unit Price
                    </th>
                    <th>
                        Quantity Sold
                    </th>
                    <th>
                        Total Price
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.OrderDetails)
                {
                    <tr>
                        <td>
                            <a asp-action="Details" asp-controller="OrderDetail" asp-route-id="@item.ID">Details</a>
                        </td>
                        <td>
                            @item.InstrumentID
                        </td>
                        <td>
                            @item.Type
                        </td>
                        <td>
                            @item.Model
                        </td>
                        <td>
                            @item.Brand
                        </td>
                        <td>
                            $@item.UnitPrice
                        </td>
                        <td>
                            @item.QuantitySold
                        </td>
                        <td>
                            $@item.TotalPrice
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Music_Web/Views/Order/Index.cshtml
@model IEnumerable<Music_Web.Models.OrderViewModel>

@{
    ViewData["Title"] = "Order Page";
    ViewBag.OActive = "active";
}
<p>
    <a asp-action="Create">Add New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th></th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CFirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmployeeID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfOrder)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalOrder)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Details" asp-route-id="@item.ID">Details</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustomerID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CFirstName)
                @Html.Display(" ")
                @Html.DisplayFor(modelItem => item.CLastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EFirstName)
                @Html.Display(" ")
                @Html.DisplayFor(modelItem => item.ELastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfOrder)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalOrder)
            </td>
        </tr>
}
    </tbody>
</table>