Music_Web/Controllers/CustomerController.cs
using DataAccess;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music_Web.Controllers
{
    public class CustomerController : Controller
    {
        private readonly MusicStore_Context _context;
        public CustomerController(MusicStore_Context context)
        {
            _context = context;
        }
        // GET: CustomerController
        public ActionResult Index()
        {
            return View(_context.Customers.ToList());
        }

        // GET: CustomerController/Create
        public ActionResult Create()
        {
            return View(new Customer());
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: CustomerController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var model = await _context.Customers.FindAsync(id);
            if (model == null) return NotFound();
            return View(model);
        }

        // POST: CustomerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Customer customer)
        {
            try
            {
                var item = _context.Customers.Find(customer.ID);
                item.FirstName = customer.FirstName;
                item.LastName = customer.LastName;
                item.Address = customer.Address;
                item.Phone = customer.Phone;
                _context.Update(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(customer);
            }
        }

        // GET: CustomerController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var model = await _context.Customers.FindAsync(id);
            if (model == null) return NotFound();
            return View(model);
        }

        // POST: CustomerController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var item = await _context.Customers.FindAsync(id);
                if (item == null) return NotFound();
                else
                {
                    _context.Customers.Remove(item);
                    var result = await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                return RedirectToAction("Details", new { id });
            }
        }
    }
}

Music_Web/Controllers/EmployeeController.cs
using DataAccess;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music_Web.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly MusicStore_Context _context;
        public EmployeeController(MusicStore_Context context)
        {
            _context = context;
        }
        // GET: EmployeeController
        public ActionResult Index()
        {
            return View(_context.Employees.ToList());
        }
        // GET: EmployeeController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var model = await _context.Employees.FindAsync(id);
            if (model == null) return NotFound();
            return View(model);
        }

        // GET: EmployeeController/Create
        public ActionResult Create()
        {
            return View(new Employee());
        }

        // POST: EmployeeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Employee employee)
        {
            try
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmployeeController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var model = await _context.Employees.FindAsync(id);
            if (model == null) return NotFound();
            return View(model);
        }

        // POST: EmployeeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Employee employee)
        {
            try
            {
                var item = _context.Employees.Find(employee.ID);
                item.FirstName = employee.FirstName;
                item.LastName = employee.LastName;
                item.Address = employee.Address;
                item.Phone = employee.Phone;
                item.Position = employee.Position;
                item.Salary = employee.Salary;
                _context.Employees.Update(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(employee);
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var item = await _context.Employees.FindAsync(id);
                if (item == null) return NotFound();
                else
                {
                    _context.Employees.Remove(item);
                    var result = await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                return RedirectToAction("Details", new { id });
            }
        }
    }
}

Music_Web/Controllers/InstrumentController.cs
using DataAccess;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music_Web.Controllers
{
    public class InstrumentController : Controller
    {
        private readonly MusicStore_Context _context;
        public InstrumentController(MusicStore_Context context)
        {
            _context = context;
        }
        // GET: InstrumentController
        public ActionResult Index()
        {
            return View(_context.Instruments.ToList());
        }
        // GET: InstrumentController/Details
        public async Task<IActionResult> Details(int id)
        {
            var model = await _context.Instruments.FindAsync(id);
            if (model == null) return NotFound();
            return View(model);
        }
        // GET: InstrumentController/Create
        public ActionResult Create()
        {
            return View(new Instrument());
        }

        // POST: InstrumentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Instrument instrument)
        {
            if (ModelState.IsValid)
            {
                _context.Add(instrument);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(instrument);
        }

        // GET: InstrumentController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var model = await _context.Instruments.FindAsync(id);
            if (model == null) return NotFound();
            return View(model);
        }

        // POST: InstrumentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Instrument instrument)
        {
            try
            {
                var item = _context.Instruments.Find(instrument.ID);
                item.Brand = instrument.Brand;
                item.InstrumentType = instrument.InstrumentType;
                item.Model = instrument.Model;
                item.UnitPrice = instrument.UnitPrice;
                item.Quantity = instrument.Quantity;
                _context.Update(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(instrument);
            }
        }
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var item = await _context.Instruments.FindAsync(id);
                if (item == null) return NotFound();
                else
                {
                    _context.Instruments.Remove(item);
                    var result = await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                return RedirectToAction("Details", new { id });
            }
        }
    }
}

Music_Web/Controllers/OrderController.cs
using DataAccess;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Models;
using Music_Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music_Web.Controllers
{
    public class OrderController : Controller
    {
        private readonly MusicStore_Context _context;
        public OrderController(MusicStore_Context context)
        {
            _context = context;
        }
        // GET: OrderController
        public ActionResult Index()
        {
            var list = _context.OrderInfos.Include(m => m.Customer).Include(m => m.Employee).ToList();
            List<OrderViewModel> model = new();
            foreach (var item in list)
            {
                var sum = _context.OrderDetails.Where(m => m.OrderInfoID == item.ID).Sum(m => m.QuantitySold * m.UnitPrice);
                var order = new OrderViewModel()
                {
                    ID = item.ID,
                    DateOfOrder = item.DateOfOrder,
                    TotalOrder = Math.Round((decimal)sum,2),
                    EmployeeID = item.Employee.ID,
                    EFirstName = item.Employee.FirstName,
                    ELastName = item.Employee.LastName,
                    CustomerID = item.Customer.ID,
                    CFirstName = item.Customer.FirstName,
                    CLastName = item.Customer.LastName,
                    CPhone = item.Customer.Phone
                };
                model.Add(order);
            }
            return View(model);
        }

        // GET: OrderController/Details/5
        public async Task<IActionResult> Details(int id)
        {

            return await ViewGenerator(id);
        }
        public async Task<IActionResult> ViewGenerator(int id)
        {
            var order = await _context.OrderInfos.FindAsync(id);
            var employee = await _context.Employees.FindAsync(order.EmployeeID);
            var customer = await _context.Customers.FindAsync(order.CustomerID);
            List<OrderDetailViewModel> details = new();
            foreach (OrderDetail item in _context.OrderDetails.Where(m => m.OrderInfoID == id))
            {
                var instrumentInfo = _context.Instruments.Find(item.InstrumentID);
                OrderDetailViewModel detailItem = new()
                {
                    ID = item.ID,
                    InstrumentID = item.InstrumentID,
                    Brand = instrumentInfo.Brand,
                    Model = instrumentInfo.Model,
                    Type = instrumentInfo.InstrumentType,
                    UnitPrice = item.UnitPrice,
                    QuantitySold = item.QuantitySold,
                    TotalPrice = Math.Round((decimal)(item.UnitPrice * item.QuantitySold),2)
                };
                details.Add(detailItem);
            }
            var sum = details.Sum(m => m.TotalPrice);
            var model = new OrderViewModel
            {
                ID = id,
                DateOfOrder = order.DateOfOrder,
                TotalOrder = Math.Round((decimal)sum,2),
                EmployeeID = employee.ID,
                EFirstName = employee.FirstName,
                ELastName = employee.LastName,
                CustomerID = customer.ID,
                CFirstName = customer.FirstName,
                CLastName = customer.LastName,
                CPhone = customer.Phone,
                OrderDetails = details
            };
            return View(model);
        }
        // GET: OrderController/Create
        public ActionResult Create()
        {
            ViewData["EmployeeID"] = new SelectList(_context.Employees, "ID", "ID");
            ViewData["CustomerID"] = new SelectList(_context.Customers, "ID", "ID");
            return View(new OrderInfo());
        }

        // POST: OrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OrderInfo orderInfo)
        {
            try
            {
                _context.Add(orderInfo);
                await _context.SaveChangesAsync();

                // Get the Id of newest item
                var newItem = await _context.OrderInfos.OrderBy(m => m.ID).LastAsync();
                return RedirectToAction(nameof(Edit), new { id = newItem.ID });
            }
            catch
            {
                ViewData["EmployeeID"] = new SelectList(_context.Employees, "ID", "ID", orderInfo.EmployeeID.ToString());
                ViewData["CustomerID"] = new SelectList(_context.Customers, "ID", "ID", orderInfo.CustomerID.ToString());

                return View(orderInfo);
            }
        }

        // GET: OrderController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var orderInfo = await _context.OrderInfos.FindAsync(id);
            ViewData["EmployeeID"] = new SelectList(_context.Employees, "ID", "ID", orderInfo.EmployeeID.ToString());
            ViewData["CustomerID"] = new SelectList(_context.Customers, "ID", "ID", orderInfo.CustomerID.ToString());
            return await ViewGenerator(id);
        }

        // POST: OrderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, OrderViewModel orderInfo)
        {
            try
            {
                var item = await _context.OrderInfos.FindAsync(id);
                item.CustomerID = orderInfo.CustomerID;
                item.EmployeeID = orderInfo.EmployeeID;
                item.DateOfOrder = orderInfo.DateOfOrder;
                _context.OrderInfos.Update(item);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewData["EmployeeID"] = new SelectList(_context.Employees, "ID", "ID", orderInfo.EmployeeID.ToString());
                ViewData["CustomerID"] = new SelectList(_context.Customers, "ID", "ID", orderInfo.CustomerID.ToString());
                return View(orderInfo);
            }
        }

        // GET: OrderController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var orderInfo = await _context.OrderInfos.FindAsync(id);
                _context.Remove(orderInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return RedirectToAction(nameof(Details), new { id });
            }
        }
    }
}

Music_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewData["Title"] - Music Store Web</title>

    <!-- Custom fonts for this template-->
    <link href="~/sbadmin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/sbadmin/css/sb-admin-2.min.css" rel="stylesheet">

    <style type="text/css"></style>
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <li>
                <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Home" asp-action="Index">
                    <div class="sidebar-brand-icon">
                        <i class="fas fa-music"></i>
                    </div>
                    <div class="sidebar-brand-text mx-3">Music Store</div>
                </a>
            </li>

            <!-- Divider -->
            <li>
                <hr class="sidebar-divider my-0">
            </li>

            <!-- Nav Item - Dashboard -->
            <li class="nav-item @ViewBag.DActive">
                <a class="nav-link" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <li>
                <hr class="sidebar-divider">
            </li>
            <li class="sidebar-heading">
                Human Resources
            </li>
            <!-- Nav Item - Employee -->
            <li class="nav-item @ViewBag.EActive">
                <a class="nav-link" asp-controller="Employee" asp-action="Index">
                    <i class="fas fa-fw fa-users"></i>
                    <span>Employee</span>
                </a>
            </li>
            <li class="nav-item @ViewBag.CActive">
                <a class="nav-link" asp-controller="Customer" asp-action="Index">
                    <i class="fas fa-fw fa-hand-holding-usd"></i>
                    <span>Customer</span>
                </a>
            </li>
            <!-- Divider -->
            <li>
                <hr class="sidebar-divider">
            </li>
            <!-- Heading -->

            <li class="sidebar-heading">
                Sales Management
            </li>
            <!-- Nav Item - Maintenance -->
            <li class="nav-item @ViewBag.IActive">
                <a class="nav-link" asp-controller="Instrument" asp-action="Index">
                    <i class="fas fa-fw fa-guitar"></i>
                    <span>Instrument</span>
                </a>
            </li>

            <!-- Nav Item - Vehicle -->
            <li class="nav-item @ViewBag.OActive">
                <a class="nav-link" asp-controller="Order" asp-action="Index">
                    <i class="fas fa-fw fa-shopping-bag"></i>
                    <span>Order</span>
                </a>

            </li>

            <!-- Sidebar Toggler (Sidebar) -->
            <li class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </li>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column min-vh-100">

            <!-- Main Content -->
            <div id="content">

                <!-- Begin Page Content -->
                <div class="container-fluid mt-4">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">@ViewData["Title"]</h1>
                    </div>
                    @RenderBody()

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright © Music Store Web 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>


    <!-- Bootstrap core JavaScript-->
    <script src="~/sbadmin/vendor/jquery/jquery.min.js"></script>
    <script src="~/sbadmin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/sbadmin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/sbadmin/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/sbadmin/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/sbadmin/js/demo/chart-area-demo.js"></script>
    <script src="~/sbadmin/js/demo/chart-pie-demo.js"></script>



</body>
</html>